CMSKreaideas/config/routes.rb
CMSKreaideas::Application.routes.draw do

  

  resources :payment_notifications

  resources :orders do
    post '/test', to: 'orders#test'
  end

  resources :line_items

  resources :carts

  devise_for :members

  root to: "store#index"

  resources :kreaideasmails
  resources :categories
  resources :products
  resources :store

  
  
  mount Refinery::Core::Engine, :at => '/'
  

end

CMSKreaideas/app/models/kreaideasmail.rb
class Kreaideasmail < ActiveRecord::Base
  attr_accessible :email, :message, :name


	validates :name,:email,:message, :presence => {:message => "debe estar presente"} 
	validates :email, :format => {:with => %r{\A[\w\.]+@\w+\.[A-Za-z]+\z}, :message => 'ingresado no es un formato válido'}
  validates :phone, :numericality => {:message => "debe ser número"}


	HUMANIZED_ATTRIBUTES = {
    :name => "El nombre",
    :email => "El correo",
    :message => "El mensaje"
 	 }

    def self.human_attribute_name(attr, options={})
    	HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  	end

end

CMSKreaideas/app/controllers/kreaideasmails_controller.rb
class KreaideasmailsController < ApplicationController
  # GET /kreaideasmails
  # GET /kreaideasmails.json
  def index
    @kreaideasmails = Kreaideasmail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kreaideasmails }
    end
  end

  # GET /kreaideasmails/1
  # GET /kreaideasmails/1.json
  def show
    @kreaideasmail = Kreaideasmail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kreaideasmail }
    end
  end

  # GET /kreaideasmails/new
  # GET /kreaideasmails/new.json
  def new
    @kreaideasmail = Kreaideasmail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kreaideasmail }
    end
  end

  # GET /kreaideasmails/1/edit
  def edit
    @kreaideasmail = Kreaideasmail.find(params[:id])
  end

  # POST /kreaideasmails
  # POST /kreaideasmails.json
  def create
    @kreaideasmail = Kreaideasmail.new(kreaideasmail_params)
    Notifier.emailcontact_received(@kreaideasmail).deliver
    respond_to do |format|
      if @kreaideasmail.save
        format.html { redirect_to @kreaideasmail, notice: 'El correo a sido enviado con éxito.' }
        format.json { render json: @kreaideasmail, status: :created, location: @kreaideasmail }
      else
        format.html { render action: "new" }
        format.json { render json: @kreaideasmail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kreaideasmails/1
  # PATCH/PUT /kreaideasmails/1.json
  def update
    @kreaideasmail = Kreaideasmail.find(params[:id])

    respond_to do |format|
      if @kreaideasmail.update_attributes(kreaideasmail_params)
        format.html { redirect_to @kreaideasmail, notice: 'EL correo a sido actualizado con éxito.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kreaideasmail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kreaideasmails/1
  # DELETE /kreaideasmails/1.json
  def destroy
    @kreaideasmail = Kreaideasmail.find(params[:id])
    @kreaideasmail.destroy

    respond_to do |format|
      format.html { redirect_to kreaideasmails_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def kreaideasmail_params
      params.require(:kreaideasmail).permit(:email, :message, :name)
    end
end

CMSKreaideas/app/helpers/kreaideasmails_helper.rb
module KreaideasmailsHelper
end

CMSKreaideas/app/views/kreaideasmails/_form.html.erb
<%= form_for(@kreaideasmail) do |f| %>
  <% if @kreaideasmail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kreaideasmail.errors.count, "error") %> prohibited this kreaideasmail from being saved:</h2>

      <ul>
      <% @kreaideasmail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

CMSKreaideas/app/views/kreaideasmails/edit.html.erb
<h1>Editing kreaideasmail</h1>

<%= render 'form' %>

<%= link_to 'Show', @kreaideasmail %> |
<%= link_to 'Back', kreaideasmails_path %>

CMSKreaideas/app/views/kreaideasmails/index.html.erb
<h1>Correos de Kreaideas</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Correo</th>
    <th>Mensaje</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kreaideasmails.each do |kreaideasmail| %>
  <tr>
    <td><%= kreaideasmail.name %></td>
    <td><%= kreaideasmail.email %></td>
    <td><%= kreaideasmail.message %></td>
    <td><%= link_to 'Show', kreaideasmail %></td>
    <td><%= link_to 'Edit', edit_kreaideasmail_path(kreaideasmail) %></td>
    <td><%= link_to 'Destroy', kreaideasmail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kreaideasmail', new_kreaideasmail_path %>

CMSKreaideas/app/views/kreaideasmails/new.html.erb
<h1>New kreaideasmail</h1>

<%= render 'form' %>

<%= link_to 'Back', kreaideasmails_path %>

CMSKreaideas/app/views/kreaideasmails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @kreaideasmail.name %>
</p>

<p>
  <b>Email:</b>
  <%= @kreaideasmail.email %>
</p>

<p>
  <b>Message:</b>
  <%= @kreaideasmail.message %>
</p>


<%= link_to 'Edit', edit_kreaideasmail_path(@kreaideasmail) %> |
<%= link_to 'Back', kreaideasmails_path %>