CMSKreaideas/config/routes.rb
CMSKreaideas::Application.routes.draw do

  

  resources :payment_notifications

  resources :orders do
    post '/test', to: 'orders#test'
  end

  resources :line_items

  resources :carts

  devise_for :members

  root to: "store#index"

  resources :kreaideasmails
  resources :categories
  resources :products
  resources :store

  
  
  mount Refinery::Core::Engine, :at => '/'
  

end

CMSKreaideas/app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy

	belongs_to :member
	accepts_nested_attributes_for :line_items
	attr_accessible :line_items_attributes
	after_save :delete_quantity_zero



	 HUMANIZED_ATTRIBUTES = {
    :quantity => "Cantidad"
 	 }

    def self.human_attribute_name(attr, options={})
    	HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  	end

  	def paypal_encrypted(return_url,notify_url)
  		values = {
  			:business=>'kreaideaspayment@gmail.com',
  			:cmd => '_cart',
  			:upload => 1,
  			:return => return_url,
  			:invoice => id,
        :notify_url => notify_url,
        :cert_id => "XTJLHK3UZBB3G"
  		}
  		line_items.each_with_index do |item, index|
  			values.merge!({
  				"amount_#{index+1}" => item.total_price,
  				"item_name_#{index+1}"=> item.product.name,
  				"item_number_#{index+1}"=> item.id,
  				"quantity_#{index+1}"=> item.quantity
  				})
  		end

  		encrypt_for_paypal(values)

  	end



    PAYPAL_CERT_PEM = File.read("#{Rails.root}/certs/paypal_cert.pem")
    APP_CERT_PEM = File.read("#{Rails.root}/certs/app_cert.pem")
    APP_KEY_PEM = File.read("#{Rails.root}/certs/app_key.pem")

    def encrypt_for_paypal(values)
      signed = OpenSSL::PKCS7::sign(OpenSSL::X509::Certificate.new(APP_CERT_PEM), OpenSSL::PKey::RSA.new(APP_KEY_PEM, ''), values.map { |k, v| "#{k}=#{v}" }.join("\n"), [], OpenSSL::PKCS7::BINARY)
      OpenSSL::PKCS7::encrypt([OpenSSL::X509::Certificate.new(PAYPAL_CERT_PEM)], signed.to_der, OpenSSL::Cipher::Cipher::new("DES3"), OpenSSL::PKCS7::BINARY).to_s.gsub("\n", "")
  end





	def add_product(product_id)
		current_item = line_items.where(:product_id => product_id).first
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(:product_id => product_id)
		end
		current_item
  	end

  	def total_price
		line_items.to_a.sum { |item| item.total_price }

	end

	def delete_quantity_zero
		LineItem.delete line_items.quantity_zero
	end




end

CMSKreaideas/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        logger.error "Intento de acceso inválido a carrito: #{params[:id]}"
        redirect_to store_index_url, :notice => 'Carrito inválido'
      else
        respond_to do |format|
          format.html # show.html.erb
          format.xml { render :xml => @cart }
        end
      end
  end
 # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)
    @cart.member_id=current_member.id
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'El carrito se a creado con éxito.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])
    #@cart=current_cart
    
    respond_to do |format|
      if @cart.update_attributes(cart_params)
        format.html { redirect_to @cart, notice: 'El carrito se a actualizado con éxito.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy

    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to(store_index_url,:notice => 'Su carrito esta vacio' ) }
      format.xml { head :ok }
    end
  end







  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def cart_params
      params.require(:cart).permit( line_items_attributes: [:id, :quantity])
    end

end

CMSKreaideas/app/helpers/carts_helper.rb
module CartsHelper
end

CMSKreaideas/app/views/carts/_cart.html.erb
<div class="cart_title" >Su carrito de compras!!</div>
<td>Id del carrito<%= cart.id%></td>
<table border="1">
<td>Cantidad</td>
<td >Producto</td>
<td >Precio Individual</td>
<td >Total de la linea</td>
<td >Eliminar linea</td>
<%= render(cart.line_items) %>
<tr class="total_line" ></tr>
</table>
<div>Total
<%= number_to_currency(cart.total_price) %></div>

<td><%= link_to 'Editar', edit_cart_path(cart) %></td>

CMSKreaideas/app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> No permiten que este carrito sea guardado:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

CMSKreaideas/app/views/carts/edit.html.erb
<h1>Editar carrito</h1>
Desgloce detallado para editar


<%= nested_form_for(@cart) do |f| %>
<table border="1">
<tr>

<th>Producto</th>
<th>Precio</th>
<th>Cantidad</th>
<th>Total de la linea</th>
</tr>
<h3> Lineas de venta</h3>
<%= f.fields_for :line_items do |task| %>
<tr>

<%= task.fields_for :product do |task2| %>

<td ><%=task2.label :name, value= "#{task2.object.name}"%></td >
<td ><%=task2.label :price, value= number_to_currency(task2.object.price, :precision => 2)%></td >
<td ><%= task.text_field :quantity %></td >
<td><%=task.label :name, value= "#{task.object.total_price}"%></td>
<% end %>
</tr>
<% end %>
</table>
Total: <%= number_to_currency(@cart.total_price) %>
<%= f.submit "Guardar cambios"%>
<% end %>
<%= link_to 'Mostrar', @cart %> |
<%= link_to 'Atrás', carts_path %>

CMSKreaideas/app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

CMSKreaideas/app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

CMSKreaideas/app/views/carts/show.html.erb
<%= render @cart %>