CMSKreaideas/config/routes.rb
CMSKreaideas::Application.routes.draw do

  

  resources :payment_notifications

  resources :orders do
    post '/test', to: 'orders#test'
  end

  resources :line_items

  resources :carts

  devise_for :members

  root to: "store#index"

  resources :kreaideasmails
  resources :categories
  resources :products
  resources :store

  
  
  mount Refinery::Core::Engine, :at => '/'
  

end

CMSKreaideas/app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index

  	@products=Refinery::Products::Product.all
  	unless current_member.nil?
  		@cart = current_cart
  	end





  end
  
end

CMSKreaideas/app/helpers/store_helper.rb
module StoreHelper
end

CMSKreaideas/app/views/store/index.html.erb
<script src="/assets/jquery.js?body=1" type="text/javascript"></script>
<script type="text/javascript">
  jQuery(document).ready(
  	function(){
  	  jQuery("#add_to_cart").click(
  	  	function(e){
  	  		var user_id = '<%= current_member%>'; 
   			if (user_id == "")
    		{
    			alert("Debe iniciar sesión para agregar productos al carrito");
    			e.preventDefault();
			 }
		}
  	  );
  	}
  );
 </script>

Id de carito en BD: <%=session[:cart]%>
<div id="user_nav">
	<% if member_signed_in?%>
	Inicio sesión como <%= current_member.email %> No es usted?
	<%= link_to "Cerrar sesión", destroy_member_session_path, :method => :delete%>
	<%else%>
		<%= link_to "Registrarse", new_member_registration_path%> o
		<%= link_to "Iniciar sesión", new_member_session_path%>
	<%end%>

	<% flash.each do |name,msg|%>
		<%= content_tag :div , msg , :id => "flash_#{name}"%>
	<%end%>


</div>
</br></br></br></br>
<%unless current_member.nil?%>
	<%= render @cart %>
  <%= current_member.id %>
  <%= @current_cart.member_id %>
  <%= form_tag "https://www.sandbox.paypal.com/cgi-bin/webscr" do %>
  <%= hidden_field_tag :cmd, "_s-xclick" %>
  <%= hidden_field_tag :encrypted, @cart.paypal_encrypted(store_index_url, payment_notifications_url) %>
  <p><%= submit_tag "Checkout" %></p>
<% end %>


  <%= button_to 'Vaciar carrito' , @cart, :method => :delete, :confirm => 'Are you sure?' %>
  <%= link_to image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), @cart.paypal_encrypted(store_index_url, orders_url)%>
<%end%>
<h1>Productos Originales</h1>
<p id="notice"><%= notice %></p>
</br>
<% @products.each do |product| %>
----------------------------------------------

<div><span class="name" >Nombre:  <%= product.name %></span></div>
<div><span class="description" >Descripción:  <%= product.description %></span></div>
<div><span class="price" >Precio: <%= number_to_currency(product.price) %></span></div>
<div><span class="code" >Código: <%= product.code %></span></div>
<div><span class="author" >Autor: <%= product.author %></span></div>
<div><span class="exchange" >Cambio: <%= product.exchange %></span></div>
<div><span class="bonus" >Bono: <%= product.bonus %></span></div>
<div><span class="stock" >Stock: <%= product.stock %></span></div>
<div><span class="subcategory" >Subcategoria: <%= product.subcategory.name %></span></div>
<div><span class="category" >Categoria: <%= product.subcategory.category.name %></span></div>
<%= button_to 'Añadir al carrito' , line_items_path(:product_id => product.id),:id=>"add_to_cart" %>

</br></br>

<% end %>